### ISSUE TITLE
beta versionen lassen sich nicht upgraden

### ISSUE THREAD

**Issue by sigi2345** [HGlab01/ioBroker.followthesun#17]
Hallo,
beta versionen lassen sich nicht upgraden

![Screenshot (2870)](https://user-images.githubusercontent.com/41079106/101339793-29e7ef00-387f-11eb-8420-e328cd29c424.png)

`$ ./iobroker upgrade followthesun
Adapter "followthesun"   is up to date.
process exited with code 0`

LG Sigi

**Comment by HGlab01** [comment]
Hallo! Ich fürchte das ist ein iobroker bug (upgrade von pre-release auf release)
Kannst du es mal mit deinstallieren / installieren veruschen?

**Comment by sigi2345** [comment]
> Hallo! Ich fürchte das ist ein iobroker bug (upgrade von pre-release auf release)
> Kannst du es mal mit deinstallieren / installieren versuchen?

Ja, so geht es, musste Instanz **und** Adapter deinstallieren.

**Comment by HGlab01** [comment]
ich möchte heute oder morgen eh eine 0.2.x launchen... dann sollte das Upgrade funktionieren.
Wenn du magst informiere ich dich?

**Comment by sigi2345** [comment]
> Wenn du magst informiere ich dich? dann kann man das mal testen

Ja bitte.

**Comment by HGlab01** [comment]
Version 0.2.1 released!
Achtung: Die bisherigen Werte sind unter die Struktur "current" gewandert

Bzgl. iob forum: ja: https://forum.iobroker.net/topic/39205/test-adapter-followthesun-v0-1-x-latest
