### ISSUE TITLE
ioBroker scheduling

### ISSUE THREAD

**Issue by Xyolyp** [HGlab01/ioBroker.followthesun#28]
Gibt es einen Hintergrund warum der Adapter dauerhaft laufen muss und nicht das interne scheduling vom ioBroker nutzt?

**Comment by HGlab01** [comment]
Der Prozess benötigt extrem geringe CPU und "rechnet" allle zwei Minuten die aktuelle Position. Alle 120 Sekunden den Prozess neu zu initialisieren ist CPU-itensiver als einen Timer auf 120 Sekunden zu haben und dann die Berechnung durchzuführen.

Wenn man die CPU Zeiten vergleicht sieht das so aus
339:58.32 iobroker.js-con
001:21.89 io.followthesun

**Comment by Xyolyp** [comment]
Das ist gut zu wissen, danke
