### ISSUE TITLE
Einheiten fehlen an einigen Datenpunkten

### ISSUE THREAD

**Issue by Xyolyp** [HGlab01/ioBroker.followthesun#30]
**Describe the bug**  
An allen Datenpunkten, die nicht im Ordner current sind fehlen die Einheiten.

**To Reproduce**  
1. Adapter installieren und Instanz starten
2. Einheiten fehlen

**Expected behavior**  
Die Datenpunkte sollten die Einheiten wie im Ordner current haben.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/13995942/102341117-ab363480-3f97-11eb-9558-27c080c1e722.png)

**Versions:**  
 - Adapter version: 0.2.4
 - JS-Controller version: 3.1.6
 - Node version: v10.22.1
 - Operating system: Debian GNU/Linux 10

**Comment by HGlab01** [comment]
Fixed in v0.2.5, available at latest
You have to delete states before starting new version, so that the unit is set accordingly.
