### ISSUE TITLE
js-controller 4.0.4 Update

### ISSUE THREAD

**Issue by Gosuwaldbear** [HGlab01/ioBroker.followthesun#308]
Version of nodejs
14.19.0

Version of ioBroker js-controller
4.0.4

Version of Adapter
0.3.8

followthesun.0 | 2022-02-06 13:36:12.142 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.142 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.142 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.142 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.141 | warn | Object current.altitude is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.141 | warn | Object current.azimuth is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.141 | warn | Object nextYear.start of winter.dusk_altitude is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.142 | warn | Object current.compass_direction is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.142 | warn | Object current.movement is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.142 | warn | Object current.lastupdate is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.140 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.140 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.140 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.140 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.141 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.141 | warn | This object will not be created in future versions. Please report this to the developer.
followthesun.0 | 2022-02-06 13:36:12.140 | warn | Object nextYear.start of winter.dawn_altitude is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.139 | warn | Object nextYear.start of winter.dawn_time is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.139 | warn | Object nextYear.start of winter.sunrise_azimuth is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.139 | warn | Object nextYear.start of winter.sunrise_altitude is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.139 | warn | Object nextYear.start of winter.sunrise_time is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.140 | warn | Object nextYear.start of winter.dawn_azimuth is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.140 | warn | Object nextYear.start of winter.dusk_time is invalid: obj.common.states has an invalid type! Expected "object", received "string"
followthesun.0 | 2022-02-06 13:36:12.140 | warn | Object nextYear.start of winter.dusk_azimuth is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by HGlab01** [comment]
will be taggled at https://github.com/ioBroker/ioBroker.js-controller/issues/1730

**Comment by HGlab01** [comment]
fixed in 0.3.9-alpha.0
https://github.com/HGlab01/ioBroker.followthesun/releases/tag/v0.3.9-alpha.0
