### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [HGlab01/ioBroker.followthesun#311]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/HGlab01/ioBroker.followthesun

- [ ] [E154] common.dependencies must contain {"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] [E405] Icon must be in the following path: https://raw.githubusercontent.com/HGlab01/ioBroker.followthesun/main/
- [ ] [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/HGlab01/ioBroker.followthesun/main/io-package.json
- [ ] [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/HGlab01/ioBroker.followthesun/main/
- [ ] [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/HGlab01/ioBroker.followthesun/main/io-package.json
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 HGlab01 <iobroker.followthesun@gmail.com>" at the start of LICENSE

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by HGlab01** [comment]
fixed!

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
