### ISSUE TITLE
Wrong value in Object solarnoon_altitude (today)

### ISSUE THREAD

**Issue by cdaerr** [HGlab01/ioBroker.followthesun#318]
**Describe the bug**  
The value in Object solarnoon_altitude (today) is different to the value calculated at current altitiude at the solarnoon_time (today)

**To Reproduce**  
1. Watch on values at calculated time

**Expected behavior**  
solarnoon_altitude (today) = current altitiude at the solarnoon_time (today)

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/98185044/153775050-9f15d38c-a948-4fa2-b24b-750f91915a6b.png)

sonnenverlauf.de calculates the following values for this time:
![grafik](https://user-images.githubusercontent.com/98185044/153775143-b494b346-6d23-4150-ace6-8cb3cc41e305.png)

**Versions:**  
 - Adapter version: 0.3.8
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: ubuntu 20.04

**Comment by HGlab01** [comment]
Hi!
Which "Interval of execution in seconds (default: 120 seconds, minimum: 10 seconds)" are you using?
For me it looks strange, that under "current" it is Feb 09 and under "today" it is Feb 08

If 25.3 or 25.1 is the right choice depends on the algorithm you are using... I tried to use the most proper one

**Comment by cdaerr** [comment]
Hi,

I use the default configuration:



I didn't change anything here.

Actually the date looks well.


Am 14.02.2022 um 15:28 schrieb HGlab:

**Comment by cdaerr** [comment]
This are the values from today, taken some minutes ago on 15. February morning.

Values for today have the date of yesterday:
![grafik](https://user-images.githubusercontent.com/98185044/153999862-6c35fb06-0100-4783-8802-3b64cfe1e44d.png)

Values for tomorrow have the date of today:
![grafik](https://user-images.githubusercontent.com/98185044/153999819-d37cfdcb-f85d-480b-bce6-fa9894594587.png)

Is there any additional debug info I can provide?

**Comment by HGlab01** [comment]
please "mose over" on solornoon today like this
![image](https://user-images.githubusercontent.com/54232526/154000973-f9fded7d-84f7-4bf6-a868-0ab16884fd4c.png)
to the the timestamp
As you see, in my installation the date was updated 34 seconds after midnight

**Comment by cdaerr** [comment]
In my installation it was updated on last adapter restart:
![grafik](https://user-images.githubusercontent.com/98185044/154001864-cb247182-d742-4b76-a62d-c67d9e88e4de.png)

![grafik](https://user-images.githubusercontent.com/98185044/154001913-1e8be87d-b590-41e7-9a9f-dbf905baa6ca.png)

The log at last **manual** restart yesterday:
![grafik](https://user-images.githubusercontent.com/98185044/154002298-2f860390-ecd2-48d4-9ce2-a0db6f0d5568.png)

Log from today after midnight:
![grafik](https://user-images.githubusercontent.com/98185044/154002450-d3383d65-3f5a-44a7-80be-732b5e364cdc.png)

**Comment by HGlab01** [comment]
still no idea whtat's going wrong. Please switch to debug mode and post the log.
Most important are the lines (dates) after "Run CalcSunData"

**Comment by cdaerr** [comment]
![grafik](https://user-images.githubusercontent.com/98185044/154005656-0d2cdb98-8f72-45f5-8d84-a466996d6842.png)

**Comment by cdaerr** [comment]
After restart values are correct:
![grafik](https://user-images.githubusercontent.com/98185044/154005875-15cde2cc-33e4-44d5-91ff-49db62b15058.png)

**Comment by HGlab01** [comment]
Can you run the adapter until tomorrow morning in debug mode?
Interesting are these log entries tomorrow after midnight. The first line date after "Run CalcSunData" is used for today, the second for yesterday, third for tomorrow etc.

**Comment by HGlab01** [comment]
Thanx for all the info!
It is a strange behavior!
First date in the log is 16th. Which is today --> ok
In the next step the time is calculated based on the date and here the unexpected happens in your installation.
This is my solar-noon from today calculated couple of seconds after midnight:
![image](https://user-images.githubusercontent.com/54232526/154210211-3517f79c-c35a-4c1c-bfa7-4facab87fbf1.png)
Can you please double check if your coordinates (latitude and longitude) are fitting to your time zone? 

Please create a new small Javascript with following content:
```
const suncalc = require('suncalc');
const config = getObject("system.adapter.javascript.0");
const lat = config.native.latitude;
const long = config.native.longitude;
log('LAT: ' + lat);
log('LONG: ' + long);
let timeStamp = new Date('2022-02-16 00:00:23');
log('TIMESTAMP: ' + timeStamp);
let times = suncalc.getTimes(timeStamp, lat, long);
log('SOLARNOON: ' + times.solarNoon);
```
and please let me know the log result :-)

**Comment by HGlab01** [comment]
Please check if this version works
https://HGlab01/ioBroker.followthesun#c3243a1e92dec5ba6e42cbef4b19fc2f73eca1b5

**Comment by cdaerr** [comment]
Version 0.3.9-alpha.3 works well:

The datapoints vom today, the 24. Feb:
![grafik](https://user-images.githubusercontent.com/98185044/155467396-8f2ff3d3-3826-44c7-9a8b-307cb5785112.png)

The debug log:
![grafik](https://user-images.githubusercontent.com/98185044/155467412-b6ec4528-1ba5-4907-bab0-f1ba87939145.png)

**Comment by HGlab01** [comment]
fixed in https://github.com/HGlab01/ioBroker.followthesun/releases/tag/v0.3.9
