### ISSUE TITLE
Remove additional menu entry

### ISSUE THREAD

**Issue by Xyolyp** [HGlab01/ioBroker.followthesun#34]
Describe the bug
Multiple different sample ui dialogs are still implemented

To Reproduce

install the adapter and start an instance
an additional main menu entry is available and the adaper pretends like it is an implementation for the history interface
Expected behavior
neither the additional main menu entry nor the history configuration should be available to the end user as they are not supported by the adapter

Screenshots & Logfiles
![image](https://user-images.githubusercontent.com/13995942/102925361-82300b00-4493-11eb-9b8f-4aead21243a4.png)
![image](https://user-images.githubusercontent.com/13995942/102980698-3d928700-4508-11eb-86ec-d531543e432e.png)

Versions:

Adapter version: 0.2.5
JS-Controller version: 3.1.6
Node version: v10.22.1
Operating system: Debian GNU/Linux 10

**Comment by HGlab01** [comment]
Which version are you using (filling the template would help!)
This menu entry should no longer exists since v0.2.3
Maybe you have to uninstall and install again

**Comment by Xyolyp** [comment]
I've updated the issue to fill the template

**Comment by HGlab01** [comment]
Thanks for the additional information!
No idea, why the menu is visible in your installation. I tried to install it again on different machines, and I did not get the menu entry.
May I kindly ask you to

1. Uninstall
2. Press STRG+F5 in the browser window (or other shortcut to force refresh)
3. check if the menu entry is gone
4. install adapter again
5. STRG+F5 again
6. verify again.

Thanks!

**Comment by Xyolyp** [comment]
I performed all the suggested steps and both the menu entry and the history settings are gone. Thank you for your effort and sorry for the inconvinience.

**Comment by HGlab01** [comment]
Good that it works as expected.Happy to support
