### ISSUE TITLE
Three minutes late

### ISSUE THREAD

**Issue by zoulhh** [HGlab01/ioBroker.followthesun#436]
**Describe the bug**  
Sunset is 18:33 but shows 18:36. Location is set correct.

1. Go to 'followthesun.0.short term.today.sunset_time'
2. Check against official services
3. See error

**Expected behavior**  
Value should be the correct sunset time

**Versions:**  
 - Adapter version: <0.3.9>
 - JS-Controller version: <4.0.23> 
 - Node version: <18.9.1> 
 - Operating system: <Debian on Raspberry Pi 4>

**Comment by HGlab01** [comment]
Hello,
I am using a library (called suncalc) for this calculation, which is used by other implementations as well.
I updated the version 0.4.0-alpha.1 to the newest library. 
I do not believe that there are any related changes in the updated lib, but feel free to test.

If it does not work you can raise a bug here
https://github.com/mourner/suncalc
