### ISSUE TITLE
movement state

### ISSUE THREAD

**Issue by Benni86** [HGlab01/ioBroker.followthesun#61]
**Let me know how I can help you **  
A clear description of the wanted functionality

Hallo,

ich habe ein Problem mit dem State "movementof the sun". In der Info habe ich das tägliche ereignis stehen um 0 Uhr das ein "cron ausgeführt" wird. Der State sunrise wird nicht gesetzt morgens! Bleibt imemr auf sunset stehen. Was könnte da für ein Fehler vorliegen. Neuinstallation ist bereits getätigt. 

lg Ben

**Comment by HGlab01** [comment]
Hallo!
Welches Intervall ist bei dir eingestellt?
![image](https://user-images.githubusercontent.com/54232526/107489868-6ee31700-6b89-11eb-990c-cae5a83a4c76.png)
Normalerweise sollte bei jedem Intervall geprüft werden ob die Sonne aufgeht oder untergeht.

Gibt es Infos im Log?

**Comment by Benni86** [comment]
Hi,

die standard 120 sekunden sind bei mir eingestellt. 
Ich sehe auch das der Adapter aktualisiert durch die grüne sChrift alle 2 Minuten, aber
der springt nie auf sunrise. Bekomme in der NAcht eine Info die einen CRON ausführt. 
Ein Adapter neustart ist auch per blocky nicht möglich, weil er nicht die Funktion besitzt neugestartet zu werden.
Wäre aber super wenn sunrise und sunset auch funktionieren würde.
Noch irgendeine Idee?

danke lg

**Comment by Benni86** [comment]
2021-02-10 00:00:44.005 - info: followthesun.0 (13556) Cronjob 'SunData' startet

ist die einzige info vom adapter, ansonsten macht er nichts!

**Comment by Benni86** [comment]
Habe ich gemacht.

Dann abwarten bis morgen. Danke schonmal

**Comment by HGlab01** [comment]
den Log kannst mir gleich schicken und es passiert ja zu Mittag auch (da wechselt es von sunrise auf sunset),
Der Log sollte aber alle 2 Minuten einen wertvollen Input liefern

**Comment by Benni86** [comment]
ja kann ich machen, aber da funktioneirt ja komischerweise.
den wechsel von sunrise zu sunset macht er einmalig, danach bleibt er auf Sunset stehen.
Erst nach dem Adapter Neustart steht der sunrise wieder da

lg

**Comment by Benni86** [comment]
So jetzt steht Sunset im state. 
Aber leider kein LOG für dich da. 

außer:
2021-02-10 11:08:44.004 - info: followthesun.0 (22567) starting. Version 0.2.6-1 in /opt/iobroker/node_modules/iobroker.followthesun, node: v12.20.1, js-controller: 3.1.6

2021-02-10 11:08:44.022 - info: followthesun.0 (22567) Calculation will be done every 120 seconds

danach kam nichts mehr

**Comment by HGlab01** [comment]
auf DebugModus umgestellt?
Bei mir sieht es so aus:

```
followthesun.0 | 2021-02-10 12:27:54.133 | debug | (13964) Sunset set
followthesun.0 | 2021-02-10 12:27:54.133 | debug | (13964) TODAYSOLARNOON: Wed Feb 10 2021 12:10:31 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 12:27:54.132 | debug | (13964) NOW: Wed Feb 10 2021 12:27:54 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 12:27:54.131 | debug | (13964) Sunposition is S
followthesun.0 | 2021-02-10 12:27:54.129 | debug | (13964) Altitude (27.4\|27.4) and/or azimuth (184.4\|185) changed
followthesun.0 | 2021-02-10 12:27:54.128 | debug | (13964) Run calcPosition
followthesun.0 | 2021-02-10 12:27:54.126 | debug | (13964) New calculation triggered by polling (every 120 seconds)
followthesun.0 | 2021-02-10 12:25:54.118 | debug | (13964) Sunset set
followthesun.0 | 2021-02-10 12:25:54.118 | debug | (13964) TODAYSOLARNOON: Wed Feb 10 2021 12:10:31 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 12:25:54.118 | debug | (13964) NOW: Wed Feb 10 2021 12:25:54 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 12:25:54.117 | debug | (13964) Sunposition is S
followthesun.0 | 2021-02-10 12:25:54.117 | debug | (13964) Altitude (undefined\|27.4) and/or azimuth (undefined\|184.4) changed
followthesun.0 | 2021-02-10 12:25:54.116 | debug | (13964) Run calcPosition
followthesun.0 | 2021-02-10 12:25:54.089 | debug | (13964) Run CalcSunData
followthesun.0 | 2021-02-10 12:25:54.089 | debug | (13964) LONGITUDE from config: 16.27354907100724
followthesun.0 | 2021-02-10 12:25:54.088 | debug | (13964) LATITUDE from config: 48.204708652920914
followthesun.0 | 2021-02-10 12:25:54.074 | info | (13964) Calculation will be done every 120 seconds
followthesun.0 | 2021-02-10 12:25:54.063 | info | (13964) starting. Version 0.2.6-1 in C:/iobroker/node_modules/iobroker.followthesun, node: v12.18.0, js-controller: 3.1.4
```

**Comment by Benni86** [comment]
das ist doch bei der installation vom adapter lediglich das "Häkchen" setzen bei Debug.
oder muss ich noch was machen?

**Comment by Benni86** [comment]
followthesun.0 | 2021-02-10 13:26:40.192 | debug | (29072) Sunset set
-- | -- | -- | --
followthesun.0 | 2021-02-10 13:26:40.192 | debug | (29072) TODAYSOLARNOON: Wed Feb 10 2021 12:49:07 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 13:26:40.191 | debug | (29072) NOW: Wed Feb 10 2021 13:26:40 GMT+0100 (GMT+01:00)
followthesun.0 | 2021-02-10 13:26:40.191 | debug | (29072) Sunposition is S
followthesun.0 | 2021-02-10 13:26:40.190 | debug | (29072) Altitude (undefined\|24.6) and/or azimuth (undefined\|190.2) changed
followthesun.0 | 2021-02-10 13:26:40.190 | debug | (29072) Run calcPosition
followthesun.0 | 2021-02-10 13:26:40.159 | debug | (29072) Run CalcSunData
followthesun.0 | 2021-02-10 13:26:40.159 | debug | (29072) LONGITUDE from config: 6.620843002232245
followthesun.0 | 2021-02-10 13:26:40.159 | debug | (29072) LATITUDE from config: 50.582438650880874
followthesun.0 | 2021-02-10 13:26:40.150 | info | (29072) Calculation will be done every 120 seconds
followthesun.0 | 2021-02-10 13:26:40.134 | info | (29072) starting. Version 0.2.6-1 in /opt/iobroker/node_modules/iobroker.followthesun, node: v12.20.1, js-controller: 3.1.6
followthesun.0 | 2021-02-10 13:26:39.621 | debug | (29072) statesDB connected
followthesun.0 | 2021-02-10 13:26:39.620 | debug | (29072) States connected to redis: 127.0.0.1:9000
followthesun.0 | 2021-02-10 13:26:39.614 | debug | (29072) States create System PubSub Client
followthesun.0 | 2021-02-10 13:26:39.612 | debug | (29072) States create User PubSub Client
followthesun.0 | 2021-02-10 13:26:39.606 | debug | (29072) Redis States: Use Redis connection: 127.0.0.1:9000
followthesun.0 | 2021-02-10 13:26:39.605 | debug | (29072) objectDB connected
followthesun.0 | 2021-02-10 13:26:39.601 | debug | (29072) Objects connected to redis: 127.0.0.1:9001
followthesun.0 | 2021-02-10 13:26:39.592 | debug | (29072) Objects client initialize lua scripts
followthesun.0 | 2021-02-10 13:26:39.584 | debug | (29072) Objects create User PubSub Client
followthesun.0 | 2021-02-10 13:26:39.583 | debug | (29072) Objects create System PubSub Client
followthesun.0 | 2021-02-10 13:26:39.580 | debug | (29072) Objects client ready ... initialize now
followthesun.0 | 2021-02-10 13:26:39.543 | debug | (29072) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.buanet-iobroker1 | 2021-02-10 13:26:39.127 | info | instance system.adapter.followthesun.0 started with pid 29072
host.buanet-iobroker1 | 2021-02-10 13:26:36.620 | info | instance system.adapter.followthesun.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
followthesun.0 | 2021-02-10 13:26:36.108 | info | (22567) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
followthesun.0 | 2021-02-10 13:26:36.107 | info | (22567) terminating
followthesun.0 | 2021-02-10 13:26:36.107 | info | (22567) cleaned everything up...
followthesun.0 | 2021-02-10 13:26:36.106 | info | (22567) Got terminate signal TERMINATE_YOURSELF

sry war nur in Info Modus

**Comment by HGlab01** [comment]
ok, die Implementierung ist fehlerhaft. Ich schau mir das mal an...

**Comment by Benni86** [comment]
Zu deiner Info,

ich betreibe das ganze auf der Syn Nas mit docker. 
Glaube die Info ist ganz wichtig.

**Comment by HGlab01** [comment]
Solange deine Systemzeit stimmt sollte das kein Problem sein ;)

**Comment by HGlab01** [comment]
so sollt es klappen
https://github.com/HGlab01/ioBroker.followthesun/archive/v0.2.6-2.tar.gz

**Comment by Benni86** [comment]
jo habe es installiert


followthesun.0 | 2021-02-10 15:57:23.472 | debug | (3879) Sunset set
-- | -- | -- | --
followthesun.0 | 2021-02-10 15:57:23.472 | debug | (3879) Sun is in the lowest position after midnight
followthesun.0 | 2021-02-10 15:57:23.471 | debug | (3879) NadirInMinutes: 49.11666666666667
followthesun.0 | 2021-02-10 15:57:23.471 | debug | (3879) SolarNoonInMinutes: 769.1166666666667
followthesun.0 | 2021-02-10 15:57:23.471 | debug | (3879) NowInMinutes: 957.3833333333333
followthesun.0 | 2021-02-10 15:57:23.471 | debug | (3879) Sunposition is SW
followthesun.0 | 2021-02-10 15:57:23.470 | debug | (3879) Altitude (13.4\|13.1) and/or azimuth (226.5\|227) changed
followthesun.0 | 2021-02-10 15:57:23.470 | debug | (3879) Run calcPosition
followthesun.0 | 2021-02-10 15:57:23.469 | debug | (3879) New calculation triggered by polling (every 120 seconds)
followthesun.0 | 2021-02-10 15:55:23.471 | debug | (3879) Sunset set
followthesun.0 | 2021-02-10 15:55:23.471 | debug | (3879) Sun is in the lowest position after midnight
followthesun.0 | 2021-02-10 15:55:23.470 | debug | (3879) NadirInMinutes: 49.11666666666667
followthesun.0 | 2021-02-10 15:55:23.470 | debug | (3879) SolarNoonInMinutes: 769.1166666666667
followthesun.0 | 2021-02-10 15:55:23.470 | debug | (3879) NowInMinutes: 955.3833333333333
followthesun.0 | 2021-02-10 15:55:23.470 | debug | (3879) Sunposition is SW
followthesun.0 | 2021-02-10 15:55:23.469 | debug | (3879) Altitude (undefined\|13.4) and/or azimuth (undefined\|226.5) changed
followthesun.0 | 2021-02-10 15:55:23.469 | debug | (3879) Run calcPosition
followthesun.0 | 2021-02-10 15:55:23.439 | debug | (3879) Run CalcSunData
followthesun.0 | 2021-02-10 15:55:23.438 | debug | (3879) LONGITUDE from config: 6.620843002232245
followthesun.0 | 2021-02-10 15:55:23.438 | debug | (3879) LATITUDE from config: 50.582438650880874
followthesun.0 | 2021-02-10 15:55:23.427 | info | (3879) Calculation will be done every 120 seconds
followthesun.0 | 2021-02-10 15:55:23.415 | info | (3879) starting. Version 0.2.6-2 in /opt/iobroker/node_modules/iobroker.followthesun, node: v12.20.1, js-controller: 3.1.6
followthesun.0 | 2021-02-10 15:55:22.874 | debug | (3879) statesDB connected
followthesun.0 | 2021-02-10 15:55:22.874 | debug | (3879) States connected to redis: 127.0.0.1:9000
followthesun.0 | 2021-02-10 15:55:22.870 | debug | (3879) States create System PubSub Client
followthesun.0 | 2021-02-10 15:55:22.868 | debug | (3879) States create User PubSub Client
followthesun.0 | 2021-02-10 15:55:22.865 | debug | (3879) Redis States: Use Redis connection: 127.0.0.1:9000
followthesun.0 | 2021-02-10 15:55:22.863 | debug | (3879) objectDB connected
followthesun.0 | 2021-02-10 15:55:22.860 | debug | (3879) Objects connected to redis: 127.0.0.1:9001
followthesun.0 | 2021-02-10 15:55:22.851 | debug | (3879) Objects client initialize lua scripts
followthesun.0 | 2021-02-10 15:55:22.850 | debug | (3879) Objects create User PubSub Client
followthesun.0 | 2021-02-10 15:55:22.849 | debug | (3879) Objects create System PubSub Client
followthesun.0 | 2021-02-10 15:55:22.848 | debug | (3879) Objects client ready ... initialize now
followthesun.0 | 2021-02-10 15:55:22.817 | debug | (3879) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.buanet-iobroker1 | 2021-02-10 15:55:22.397 | info | instance system.adapter.followthesun.0 started with pid 3879
host.buanet-iobroker1 | 2021-02-10 15:55:20.465 | info | Update repository "Stable (default)" under "http://download.iobroker.net/sources-dist.json"
host.buanet-iobroker1 | 2021-02-10 15:55:20.363 | info | iobroker exit 0
host.buanet-iobroker1 | 2021-02-10 15:55:19.876 | info | instance system.adapter.followthesun.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
followthesun.0 | 2021-02-10 15:55:19.363 | info | (29072) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
followthesun.0 | 2021-02-10 15:55:19.363 | info | (29072) terminating
followthesun.0 | 2021-02-10 15:55:19.362 | info | (29072) cleaned everything up...
followthesun.0 | 2021-02-10 15:55:19.361 | info | (29072) Got terminate signal TERMINATE_YOURSELF
host.buanet-iobroker1 | 2021-02-10 15:55:19.360 | info | stopInstance system.adapter.followthesun.0 send kill signal
host.buanet-iobroker1 | 2021-02-10 15:55:19.359 | info | stopInstance system.adapter.followthesun.0 (force=false, process=true)
host.buanet-iobroker1 | 2021-02-10 15:55:19.350 | info | iobroker Update "system.adapter.followthesun.0"
host.buanet-iobroker1 | 2021-02-10 15:55:19.234 | info | iobroker upload [0] followthesun.admin /opt/iobroker/node_modules/iobroker.followthesun/admin/admin.d.ts admin.d.ts video/mp2t
host.buanet-iobroker1 | 2021-02-10 15:55:19.177 | info | iobroker upload [1] followthesun.admin  /opt/iobroker/node_modules/iobroker.followthesun/admin/followthesun.png  followthesun.png image/png
host.buanet-iobroker1 | 2021-02-10 15:55:19.123 | info | iobroker upload [2] followthesun.admin  /opt/iobroker/node_modules/iobroker.followthesun/admin/index_m.html  index_m.html text/html
host.buanet-iobroker1 | 2021-02-10 15:55:19.068 | info | iobroker upload [3] followthesun.admin /opt/iobroker/node_modules/iobroker.followthesun/admin/style.css style.css text/css
host.buanet-iobroker1 | 2021-02-10 15:55:19.015 | info | iobroker upload [4] followthesun.admin  /opt/iobroker/node_modules/iobroker.followthesun/admin/tsconfig.json  tsconfig.json application/json
host.buanet-iobroker1 | 2021-02-10 15:55:18.945 | info | iobroker upload [5] followthesun.admin  /opt/iobroker/node_modules/iobroker.followthesun/admin/words.js words.js  application/javascript
host.buanet-iobroker1 | 2021-02-10 15:55:18.861 | info | iobroker 38 packages are looking for funding  run `npm fund` for details
host.buanet-iobroker1 | 2021-02-10 15:55:17.883 | info | iobroker + iobroker.followthesun@0.2.6-2updated 1 package in 12.789s
host.buanet-iobroker1 | 2021-02-10 15:55:04.272 | info | iobroker npm install  https://github.com/HGlab01/ioBroker.followthesun/archive/v0.2.6-2.tar.gz  --loglevel error --prefix "/opt/iobroker" (System call)
host.buanet-iobroker1 | 2021-02-10 15:55:04.270 | info | iobroker NPM version: 6.14.10
host.buanet-iobroker1 | 2021-02-10 15:55:03.985 | info | iobroker install https://github.com/HGlab01/ioBroker.followthesun/archive/v0.2.6-2.tar.gz
host.buanet-iobroker1 | 2021-02-10 15:55:02.942 | info | iobroker url "https://github.com/HGlab01/ioBroker.followthesun/archive/v0.2.6-2.tar.gz" --debug

**Comment by HGlab01** [comment]
du kannst es mal bis morgen auch ohne Debug-Mode laufen lassen und mal schauen ob es funktioniert

**Comment by Benni86** [comment]
Super schonmal vielen lieben Dank. 

Melde mich

**Comment by Benni86** [comment]
Guten Morgen.

also der Wechsel zu sunrise scheint zu funktionieren. 
War nur überrascht, das es schon um 0:50 Uhr passiert ist. 
Kann ich die sunrise und sunset Funktion nicht so nutzen, das die zu meinen Längen und Breitengrade 
passen und mir die Sonne tatsächliche Anzeigen. Denn normalerweise wäre Sonnenaufgang heute bei mir 7:23 Uhr
und Untergang um 17:23 Uhr. Oder versteh ich den Adapter falsch?

lg

**Comment by HGlab01** [comment]
Sunrise bedeutet, dass die Sonne wieder beginnt aufzugehen Das ist somit rund um Mitternacht
Sunset bedeutet, dass sie wieder snkt. Das ist somit rund um Mittag. Es sind eben Movements (Bewegungen) und keine Zeitpunkte
Was du willst ist eigentlich den Zeitpunkt wissen oder sowas wie "Sunset reached", richtig?

Du kannst mir ja mal deinen Anwendungsfall schildern und dann kann ich mir überlegen ob/wie man das im Adapter unterstützen kann.

**Comment by Benni86** [comment]
Genau.

also ich habe den Anwendungsfall, das ich eigentlich mit dem Adapter bei mir die TAG/Nachtumschaltung realisiere. Sprich die Taster werden abgedunkelt und Treppenlicht einschalten usw.... umgekehrt natürlich dann auch, wenn die Sonne wieder da ist.

**Comment by HGlab01** [comment]
verstehe, warum nutzt du dafür dann nicht followthesun.x.current.altitude in Kombination mit followthesun.x.current.movement.

So in der Art:
if (altitude = 1 && movement = 'sunrise') {mach was immer bei Sonnenaufgang geschehen soll}

if (altitude = 1 && movement = 'sunset') {mach was immer bei Sonnenuntergang geschehen soll}

Vorteil hier ist, du kannst selbst definieren wann Sonnenuntergang ist. Das kann bei 1 oder bei -2 oder wo auch immer sein.
Es gibt ja auch nicht den einen Sonnenuntergangszeitpunkt sondern ca. 10 verschiedene, zB sunset, dusk, nautical dusk, night etc.

**Comment by HGlab01** [comment]
fixed in v0.2.7
