### ISSUE TITLE
Configuration dialog for separate coordinates to follow the sun

### ISSUE THREAD

**Issue by kaeptn-blau** [HGlab01/ioBroker.followthesun#615]
Hi guys,

I´am running one iobroker to monitor/manage our house and our holiday home which are connected via vpn.
So I would suggest a configuration dialoge to use the coordinates from the iobroker-installation
or the possibility to enter separate coordinates (of the holiday home).
So I could run two separate follow-the-sun-instances to calculate the times for each house.

Thanks for your work!

Kind regards

Ecki

**Comment by HGlab01** [comment]
can be tested by installing in the shell
`iob upgrade iobroker.followthesun@0.5.0-alpha.0`

**Comment by kaeptn-blau** [comment]
thank you for your fast reaction, it works.

two suggestions (just beautifying) : 
1. Notation of coordinates. The system settings write it with decimal dot eg 51.123, the configuration dialog requests 51,123 as using the "." empties the field
2. maybe a checkbox would it make more consistent to other adapters

O Use System Settings, (default is hooked)

and if hook is removed the two fields appear to enter the coordinates.

Best regards

Ecki

**Comment by kaeptn-blau** [comment]
perfect. Thats it. 

Thanks a lot

Ecki
