### ISSUE TITLE
SunRise and SunSet Position and Time

### ISSUE THREAD

**Issue by joelli007** [HGlab01/ioBroker.followthesun#67]
Would love to get additional datapoints for position and time for sunrise and sunset. 
Recently I switched over from using suncalc to your adapter after I had issues with suncalc. Your adapter seems to be more accurate. I am using your adapter to control my window blinds and show the sun position in vis.
Thanks in advance.

**Comment by HGlab01** [comment]
you can test the version
https://github.com/HGlab01/ioBroker.followthesun/archive/v0.3.0-0.tar.gz
by insalling via the "cat" ![image](https://user-images.githubusercontent.com/54232526/107873015-520f5200-6eaf-11eb-8caf-3660ea80cef5.png) in the adapter tab.

**Comment by joelli007** [comment]
I just installed it and it works like a charm right away!
I compared it against www.sonnenverlauf.de and found very low discrepancy below 0.5 degree.
For me very sufficient!
Thank you very much for your fast support!
Kind regards,
joelli007

**Comment by HGlab01** [comment]
I will release a version in the next couple of days
